name: Rust CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read
  actions: read
  checks: read

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - name: Checkout Code
        uses: actions/checkout@v4

      # Install Rust Toolchain (Stable)
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy, rustfmt

      # Cache Dependencies
      - name: Cache Dependencies
        uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true

      # Install System Dependencies
      - name: Install System Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libasound2-dev libudev-dev pkg-config

      # ✅ Automatically Update Dependencies
      - name: Update Rust Dependencies
        run: cargo update

      # Check Formatting
      - name: Check Formatting
        run: cargo fmt -- --check

      # Lint Code (Clippy)
      - name: Lint with Clippy
        run: cargo clippy -- -D warnings

      # Build the Rust project
      - name: Build
        run: cargo build --verbose

      # Run Tests (All Features)
      - name: Run Tests
        run: cargo test --all-features --verbose

      # Run Documentation Tests
      - name: Run Doc Tests
        run: cargo test --doc
