name: QuantumFuse Build & Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install ALSA (Only if Feature is Enabled)
        if: contains(github.event.inputs.features, 'audio')
        run: |
          sudo apt-get update
          sudo apt-get install -y libasound2-dev pkg-config

      - name: Build (All Features)
        run: cargo build --verbose --all-features

      - name: Run Tests
        run: cargo test --verbose
